export const ADD_WEDDINGHALL_TO_CART = 'add_wd_to_cart'
export const DELETE_WEDDINGHALL_CART_ITEM = 'del_wd_cart_item'
export const ADD_MENU_TO_CART = 'add_mn_to_cart'
export const DELETE_MENU_CART_ITEM = 'del_mn_cart_item'
export const ADD_SERVICE_TO_CART = 'add_sv_to_cart'
export const DELETE_SERVICE_CART_ITEM = 'del_sv_cart_item'